import Head from "next/head";
import Header from "@/Components/Header/header";
import About from "@/Components/About";
import ContactForm from "@/Components/ContactForm";
import Footer from "@/Components/Footer/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-50">
        <Header />
        <main className="container mx-auto p-4">
          <About />
          <ContactForm />
        </main>
        <Footer />
      </div>
    </>
  );
}
